### ISSUE TITLE
Sandbox  value false.

### ISSUE THREAD

**Issue by luisrossi** [vinicinbgs/autentique-v2#10]
em src\Documents.php:20

Estava assim: $this->sandbox = getenv('AUTENTIQUE_DEV_MODE') ? 'true' : 'false';
Alterei para isso:  $this->sandbox = env('AUTENTIQUE_DEV_MODE') == true ? 'true' : 'false';

Pois ele sempre estava entrando como false e dessa forma funciona.

**Comment by vini-md** [comment]
Voce esta usando algum framework?

Obrigado @luisrossi

**Comment by luisrossi** [comment]
Sim. Estou usando Laravel na versão 8

**Comment by magnosanttana** [comment]
@luisrossi vc teve sucesso na criação de documento? Consegui listar, mas na hora de criar da acesso não autorizado e são as mesmas credenciais...

**Comment by viniciusmdutra** [comment]
@magnosanttana conseguiu solucionar o problema?
