### ISSUE TITLE
Is this command really correct? 

### ISSUE THREAD

**Issue by Adiniz21** [vinicinbgs/autentique-v2#18]
Is this command really correct? Because I'm trying to run the same and it doesn't run warning that there is no command in composer.
![image](https://user-images.githubusercontent.com/81169291/170359368-4b3e54e2-05e2-4008-9297-260be5ecb942.png)
![image](https://user-images.githubusercontent.com/81169291/170359400-626c2744-cb7a-4b2e-896b-ec5f5323c1fe.png)

**Comment by vini-md** [comment]
Hi Artur, sorry I made a typo mistake, just run

composer require vinicinbgs/autentique-v2

**Comment by vini-md** [comment]
I fixed in the README.md: [commit link](https://github.com/vinicinbgs/autentique-v2/commit/aa80e9feadcabc11f037e8bea70f7d50c082acc8)

give me a feedback if it works and I will close this issue

thank you :)

**Comment by Adiniz21** [comment]
Thanks
