### ISSUE TITLE
I put the api token in the .env

### ISSUE THREAD

**Issue by Adiniz21** [vinicinbgs/autentique-v2#19]
I put the api token in the .env, but when I put the command to generate the document it gives error 400 preventing the api from working, any suggestions for a solution?

![image](https://user-images.githubusercontent.com/81169291/170368692-957864bc-7080-4a25-a4d9-cd0f585391a9.png)
![image](https://user-images.githubusercontent.com/81169291/170369296-481ffc8d-123c-4f52-84f8-0f5f5a66d9de.png)

**Comment by vini-md** [comment]
Try it https://github.com/vinicinbgs/autentique-v2/issues/2

**Comment by vini-md** [comment]
Did you have a file? ./dummy.pdf?

Its possible return false if you not have any pdf to send

**Comment by Adiniz21** [comment]
But wouldn't this function create a document?

**Comment by vini-md** [comment]
Based in a pdf.

You need for example send a contract in pdf to be sign on the autentique platform.

The Autentique only sign documents  in pdf format with digital signature.

**Comment by vini-md** [comment]
It worked?
