### ISSUE TITLE
Internal server error - Create a new document

### ISSUE THREAD

**Issue by leandrolic** [vinicinbgs/autentique-v2#20]
When I try to create a document I get the message below:
`{"errors":[{"message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":1,"column":108}],"path":["createDocument"]}],"data":{"createDocument":null}}`
NOTE: the other functions are working normally.

Code:

```
$documents = new Documents($_ENV['AUTENTIQUE_TOKEN']);
$folders = new Folders($_ENV['AUTENTIQUE_TOKEN']);
$attributes = [
		 'document' => [
			 'name' => 'NOME DO DOCUMENTO',
		 ],
		 'signers' => [
			 [
				 'email' => 'teste@gmail.com',
				 'action' => 'SIGN',
				 ],
			],
		 'file' =>  Storage::path('teste.pdf');
	 ];
print_r(json_encode($documents->create($attributes)));
```

How can i fix that?

**Comment by vini-md** [comment]
Put a debug ```dd($response)``` or ```var_dump($response);exit();``` in this line and post the result here
https://github.com/vinicinbgs/autentique-v2/blob/master/src/utils/Api.php#L92

**probably path in your project:** vendor/vinicinbgs/autentique-v2/src/utils/Api.php

And check if the ```Storage::path('teste.pdf')``` are give the right path for the file

**Comment by leandrolic** [comment]
Return the same error:

`"{"errors":[{"message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":1,"column":108}],"path":["createDocument"]}],"data":{"createDocument":null}} ◀"`

**Comment by leandrolic** [comment]
The error was in the file name. I was using "teste-01.pdf". When I removed the caracter "-" the api worked.
Thanks

**Comment by vini-md** [comment]
Great! thank you too :) have a nice day

I will close the issue
