### ISSUE TITLE
Laravel and vlucas/phpdotenv

### ISSUE THREAD

**Issue by alexmontoanelli** [vinicinbgs/autentique-v2#35]
After Laravel 8,  they  bumped they requiriments for  "vlucas/phpdotenv": "^5.X",

So, with the latests version of Laravel, i can upgrade to latest version of this library, thats
needs only vlucas/phpdotenv : 4.X

**Comment by vini-md** [comment]
I dont know if I got it...

Do you have an issue or are you just explaining that not have?

**Comment by alexmontoanelli** [comment]
Sorry, after try to reproduce again, we see our fault.

**Comment by alexmontoanelli** [comment]
Reopen

The version 3.1.1 has "vlucas/phpdotenv": "^4.1" in the *require-dev* section.

While the version 3.1.2 and 3.1.3 has vlucas/phpdotenv in *require* section.

If you install a clean Laravel 10, and install this package, the 3.1.1 will be installed.

Then if you try to upgrade to 3.1.2 and 3.1.3, a conflict will occur, because, Laravel 10, require vlucas/phpdotenv 5
while this package, require vlucas/phpdotenv 4.

![Screenshot 2023-12-15 at 08 36 19](https://github.com/vinicinbgs/autentique-v2/assets/4535817/dea57a7b-0417-456d-b679-10bd7f0f4dff)
 
![Screenshot 2023-12-15 at 08 37 44](https://github.com/vinicinbgs/autentique-v2/assets/4535817/90ab8c19-8a1d-44e4-ac72-1f6d9fe20df8)

![Screenshot 2023-12-15 at 08 38 11](https://github.com/vinicinbgs/autentique-v2/assets/4535817/6ef1f26f-9924-4317-bf9b-dd749beff5b2)

![Screenshot 2023-12-15 at 08 39 08](https://github.com/vinicinbgs/autentique-v2/assets/4535817/2d1955f6-534a-4446-95c9-f0ef52b1c298)

**Comment by vini-md** [comment]
Got it, I will check a way to solve it

Thank you now for the explanation

**Comment by vini-md** [comment]
Please install the new version on https://github.com/vinicinbgs/autentique-v2/releases/tag/v4.0.0

And let me know if your error stopped occurring

**Comment by alexmontoanelli** [comment]
All good in 4.0.
Thanks.

**Comment by vini-md** [comment]
Thank you.
