### ISSUE TITLE
Maximum execution time of 60 seconds exceeded in src/utils/Api.php:92

### ISSUE THREAD

**Issue by kkpriscila** [vinicinbgs/autentique-v2#38]
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/2fb1df77-0f8f-4b82-830f-f99d7de04ad2)

Estou tentando usar a api com laravel 9 e php8.2.9 e estou tendo esse erro como resposta. Help-me, please!

**Comment by vini-md** [comment]
Pode me dar detalhes de como você implementou a chamada?
Me mostra seu `.env` (Omite o Token)

**Comment by kkpriscila** [comment]
@vinicinbgs posso dar detalhe sim... segue abaixo meu .env e parte do meu código.. Utilizo laravel 9.52.16 e PHP 8.2.9
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/b526fd76-6824-420e-a771-e5afbc6d8a42)

e meu código com dá o erro é esse:
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/37303984-f814-4993-8d1b-29fdcbe7a09f)
além de dá o **_use vinicinbgs\Autentique\Documents;_**  na classe..

Meus atributos que foram montados dinamicamente chegam assim pelo dd:
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/e06f3a1b-65e0-4967-93ca-e433bcb7edf7)

**Comment by vini-md** [comment]
Qual versão da lib autentique vc ta usando, me mostra no composer.json?

Se tiver usando diferente da v4.0.0

Atualiza pra ela

Estranho o comportamento, aparentemente ta tudo ok

Investigue se o token esta chegando corretamente com os valores tbm.

Verifique se o caminho do file está correto.

Verifique se o servidor que está tentando acessar a url do autentique tem alguma regra de firewall que o impede.

**Comment by kkpriscila** [comment]
a lib é a mais atual:  "vinicinbgs/autentique-v2": "4.0"

o token tentei tanto vindo do .env qto buscando dinamicamente e conferi se ele estava chegando. Tentei tanto com 
AUTENTIQUE_DEV_MODE="false" e AUTENTIQUE_DEV_MODE="true"

o caminho do arquivo esta certissimo que eu abri ele antes.. fiz com os atributos fixos como no exemplo da documentação só mudando os emails e até agora não consegui sair desse erro que está no create. 
Mudei meu código para usar função listAll e funcionou listando os documentos dessa minha conta com token vindo do .env e dinamicamente.
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/5ef7aacd-3975-46fe-8872-a0cd27833b7a)
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/4cbec0de-ea3c-4b74-adaa-5aa7b6581888)

**Comment by kkpriscila** [comment]
@vinicinbgs era o caminho do arquivo mesmo que estava pra um servidor de teste local. Me desculpe aí o transtorno mas agradeço imensamente pela ajuda

**Comment by vini-md** [comment]
@kkpriscila sem problemas! 
Que bom que deu tudo certo, obrigado por avisar!
