### ISSUE TITLE
Acrescentar na api alterar documento

### ISSUE THREAD

**Issue by kkpriscila** [vinicinbgs/autentique-v2#39]
Tem como fazer nessa api a parte de alterar documento como adicionar ou excluir signatários, alterar Configurações adicionais

**Comment by vini-md** [comment]
Vou adicionar essa funcionalidade

**Comment by vini-md** [comment]
@kkpriscila 

Adicionei na versão `v4.1.0` a feature de update do documento.

Veja na doc: https://beadev.net/autentique-v2/documents#4---update-document

**Comment by kkpriscila** [comment]
Colega @vinicinbgs nem acredito que vc já fez isso... está de parabéns pacote da api está ficando top.. Vou testa aqui hoje.

**Comment by kkpriscila** [comment]
Pra ficar show faltou só permitir adicionar e excluir signatários. o adicionar seria no próprio update podendo enviar a "signers" =>  nos $attributes. Tentei assim mas acho que não era esperado.
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/61c9215e-8f8c-4108-aa7c-ee40f5ead479)


Já o excluir signatário só é permitido se ele ainda não assinou o documento, aí acho q teria que ser uma função(método) a parte
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/c87654a1-b568-4716-afc0-652d5f13c34e)

**Comment by vini-md** [comment]
Dei uma olhada aqui, o `adicionar signatário` vai precisar ficar em um metódo separado, a `mutation` que o `autentique` provê é diferente da de `update`

A de `excluir signatário` tbm..

Vou adicionar esses **2 novos metódos** e aviso

**Comment by vini-md** [comment]
Essa semana (até 12/01/2024) vai sair a release contemplando essas funcionalidades

**Comment by kkpriscila** [comment]
Aguardando ansiosa...

**Comment by vini-md** [comment]
Adicionado na versäo `v4.2.0`

- https://beadev.net/autentique-v2/documents#9---create-signer-to-document
- https://beadev.net/autentique-v2/documents#10---remove-signer-from-document

**Comment by kkpriscila** [comment]
vlw d++ vou testar aqui

**Comment by vini-md** [comment]
> vlw d++ vou testar aqui

show! me avise se funcionou corretamente
