### ISSUE TITLE
Env vars

### ISSUE THREAD

**Issue by joaovdiasb** [vinicinbgs/autentique-v2#43]
Existe um problema quando o servidor possui algumas configurações de segurança ativas, não permitindo acessar $_ENV
![CleanShot 2024-01-16 at 12 48 48@2x](https://github.com/vinicinbgs/autentique-v2/assets/51106311/2b331858-c802-49e3-9808-4c811bbaa5ca)

`development.ERROR: AUTENTIQUE_URL cannot be empty`

Local esta funcionando normalmente

**Comment by vini-md** [comment]
estranho, me parece que ele não carregou nenhuma env sua...

tenta inferir o token na hora que ta instanciando a classe `Documents`

```pho
$token = "YOUR_ALTERNATIVE_TOKEN";
$documents = new Documents($token);
```

pq em tese a lib não vai dar load no .env, tem q ser feito pela sua aplicação mesmo. Se no local ela ta fazendo... precisamos encontrar qual config é que esta impedindo o servidor de carregar

me de mais alguns detalhes de qual cloud, serviço etc..

**Comment by vini-md** [comment]
se for Docker, me mostra seu Dockerfile

**Comment by joaovdiasb** [comment]
O deploy foi feito usando o serviço virtiz.com (é semelhante ao laravel forge) tentei inferir e deu o mesmo erro, acessando as variáveis de ambiente através do helper config('...') do laravel funciona normalmente

**Comment by vinicinbgs** [comment]
não conheço esse serviço... mas se ele esta bloqueando o carregamento das variaveis vc terá que mudar a implementação para algo nesse sentido:

```php
$token = config('TOKEN_AUTENTIQUE');
$documents = new Documents($token);
```

A lib da opção de automaticamente pegar do `$_ENV` ou vc mesmo passar na instância do `new Documents(TOKEN_AQUI)`

**Comment by vini-md** [comment]
Vou habilitar alguma forma de passar a URL do autentique inferindo em alguma classe. Só notei depois que vc tava falando do `AUTENTIQUE_URL`...  Tinha presumido que fosse o TOKEN...

Consigo entregar uma release corrigindo isso até amanhã.

**Comment by joaovdiasb** [comment]
> Vou habilitar alguma forma de passar a URL do autentique inferindo em alguma classe. Só notei depois que vc tava falando do `AUTENTIQUE_URL`... Tinha presumido que fosse o TOKEN...

Seria ótimo, iria resolver aqui

**Comment by vini-md** [comment]
Gerei uma versão `4.3.0` onde não precisa informar mais o `AUTENTIQUE_URL` que ele ja tem valor default.

Adicionei alguns métodos `set` pra conseguir manipular os valores caso não use as `$_ENV`.

Da uma olhada na doc que ta detalhada la, https://beadev.net/autentique-v2/documents.

**Comment by vini-md** [comment]
Vou fechar a issue, mas caso encontre algum problema ou ela funcione me avisa via comentário nela mesmo. Blz?

**Comment by joaovdiasb** [comment]
Funcionou certinho, agradeço a atenção! caso alguém tenha dúvida, fiz a implementação utilizando a config de services do laravel 
![CleanShot 2024-01-17 at 16 37 08@2x](https://github.com/vinicinbgs/autentique-v2/assets/51106311/6fdf7958-1b13-45fe-b91a-2e075581a9e3) não precisava dar o setToken, mas enfim..

**Comment by vini-md** [comment]
> Funcionou certinho, agradeço a atenção! caso alguém tenha dúvida, fiz a implementação utilizando a config de services do laravel 
> 
> ![CleanShot 2024-01-17 at 16 37 08@2x](https://github.com/vinicinbgs/autentique-v2/assets/51106311/6fdf7958-1b13-45fe-b91a-2e075581a9e3) não precisava dar o setToken, mas enfim..
> 
> 

Opa obrigado pelo feedback, sucesso!

Vdd se quiser remover o `setToken` tem que funcionar igual
