### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by kkpriscila** [vinicinbgs/autentique-v2#45]
Esse erro está aprecendo desde ontem em localhost, nãomudei nada nessa parte. No servidor de produção que tenho o cetificado configurado, não aparece erro e funciona tudo belezinha. Como faço pra testar minha aplicação com php artisan serve ?
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/7afb6f8d-0fac-407a-a8d6-9be984cd1b13)

**Comment by edtsz** [comment]
Provavelmente a cadeia de certificados do teu servidor está desatualizada. (ou a lib de criptografia)
E _clients_ já teveram esse probelma antes com o Let's Encrypt como descrito [nessa thread](https://stackoverflow.com/questions/69387175/git-for-windows-ssl-certificate-problem-certificate-has-expired)

```* Connected to api.autentique.com.br (34.95.248.152) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=api.autentique.com.br
*  start date: Jan 21 09:21:07 2024 GMT
*  expire date: Apr 20 09:21:06 2024 GMT
*  subjectAltName: host "api.autentique.com.br" matched cert's "api.autentique.com.br"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.1
```

**Comment by luisferreirahi** [comment]
Atualizar arquivo ``ssl/ca-bundle.crt``  com [ca-bundle.crt](https://github.com/bagder/ca-bundle/blob/master/ca-bundle.crt)

**Comment by vini-md** [comment]
o @luisferreirahi abriu um PR, já estou analisando pq os testes falharam e mergeando acho que resolve esse problema do certificado

**Comment by vini-md** [comment]
um outro ponto que converge com o que o @edtsz falou, hoje a lib ta usando um certificado chumbado... poderiamos adicionar uma forma de informar o certificado no servidor, assim não teriamos esse problema quando o certificado da lib vencer

**Comment by edtsz** [comment]
eu deixo para o S.O. gerenciar os certificados que daí o comando `update-ca-certificates` geralmente resolve
provavelmente remover o atributo `CURLOPT_CAINFO` deve resolver isso

**Comment by vini-md** [comment]
@kkpriscila atualiza o pacote pra versao `v4.3.1` e me diz se está corrigido?

Antes:
```sh
$ openssl verify ca-bundle_old.crt  
C=US, O=Equifax, OU=Equifax Secure Certificate Authority
error 18 at 0 depth lookup: self-signed certificate
C=US, O=Equifax, OU=Equifax Secure Certificate Authority
error 10 at 0 depth lookup: certificate has expired
error ca-bundle (1).crt: verification failed
```

Depois:
```sh
$ openssl verify ca-bundle.crt       
ca-bundle.crt: OK
```

**Comment by vini-md** [comment]
@edtsz @luisferreirahi 

Gerei uma tag `v4.3.1` com o fix do luis, mas o problema ainda pode voltar a acontecer no futuro, caso queiram corrigir na raíz habilitando passar o certificado como uma variável de ambiente, podem abrir um PR q eu aceito (não consigo fazer agora)

@edtsz eu não sei se só removendo o `CURLOPT_CAINFO` funcionaria (se pega automatico), teriamos que testar

**Comment by kkpriscila** [comment]
> @kkpriscila atualiza o pacote pra versao `v4.3.1` e me diz se está corrigido?
> 
> Antes:
> 
> ```shell
> $ openssl verify ca-bundle_old.crt  
> C=US, O=Equifax, OU=Equifax Secure Certificate Authority
> error 18 at 0 depth lookup: self-signed certificate
> C=US, O=Equifax, OU=Equifax Secure Certificate Authority
> error 10 at 0 depth lookup: certificate has expired
> error ca-bundle (1).crt: verification failed
> ```
> 
> Depois:
> 
> ```shell
> $ openssl verify ca-bundle.crt       
> ca-bundle.crt: OK
> ```

Funcionou perfeitamente.. vlw

Engraçado que no eu servidor em produção não apareceu esse erro somento no localhost, será que no servidor ele pega os certificados do servidor?

**Comment by luisferreirahi** [comment]
Notei que essa solução não reflete nas versões anteriores, (Ex: 4.0) 
As tags não atualizam o arquivo, mantendo ``ca-bundle``  desatualizado

**Comment by vini-md** [comment]
> Notei que essa solução não reflete nas versões anteriores, (Ex: 4.0) As tags não atualizam o arquivo, mantendo `ca-bundle` desatualizado

Tem razão, pra refletir nas tags anteriores teria que:
1. `pull` uma a uma
2. Alterar o arquivo
3. `push`

**Comment by vini-md** [comment]
@kkpriscila dei uma olhada na doc e o php utiliza o `curl.cainfo` setado no `php.ini`, se não encontrar ele usa o informado pela lib

vc poderia confirmar pra mim essa info entrando no seu servidor e executando no terminal `php -i | grep curl.cainfo`, irá imprimir o caminha do certificado, ai se puder me mostrar, ajudaria a desvendar pq funciona em prod

**Comment by kkpriscila** [comment]
> @kkpriscila dei uma olhada na doc e o php utiliza o `curl.cainfo` setado no `php.ini`, se não encontrar ele usa o informado pela lib
> 
> vc poderia confirmar pra mim essa info entrando no seu servidor e executando no terminal `php -i | grep curl.cainfo`, irá imprimir o caminha do certificado, ai se puder me mostrar, ajudaria a desvendar pq funciona em prod

estranho pq no meu servidor tbm não tem nenhum setado
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/6139cd59-bb97-47cb-bd49-dc6105e464fa)

**Comment by kkpriscila** [comment]
> @kkpriscila dei uma olhada na doc e o php utiliza o `curl.cainfo` setado no `php.ini`, se não encontrar ele usa o informado pela lib
> 
> vc poderia confirmar pra mim essa info entrando no seu servidor e executando no terminal `php -i | grep curl.cainfo`, irá imprimir o caminha do certificado, ai se puder me mostrar, ajudaria a desvendar pq funciona em prod

![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/33d89779-71b1-4e28-be19-b2150a6e987c)
olhei no servidor e  ele não é setado no php.ini

**Comment by kkpriscila** [comment]
> @kkpriscila dei uma olhada na doc e o php utiliza o `curl.cainfo` setado no `php.ini`, se não encontrar ele usa o informado pela lib
> 
> vc poderia confirmar pra mim essa info entrando no seu servidor e executando no terminal `php -i | grep curl.cainfo`, irá imprimir o caminha do certificado, ai se puder me mostrar, ajudaria a desvendar pq funciona em prod

conferi no servidor e não está setado no php.ini
![image](https://github.com/vinicinbgs/autentique-v2/assets/27827100/2adc38bc-c0e0-4cfd-9a02-51884e629f12)
