### ISSUE TITLE
Question: Boolean Type no Update Documento

### ISSUE THREAD

**Issue by NandoKstroNet** [vinicinbgs/autentique-v2#48]
Fala meu povo, vocês enfrentaram o erro do tipo boolean no Update?

Tentando fazer type cast pra bool ou deixando string, recebo o mesmo erro da API GraphQL por meio do método update do Document.

Segue um pedaço da validação vindo da API:

```json
{
    "errors": [
        {
            "message":"Variable \"$document\" got invalid value {\"name\":\"NOME_DOCUMENTO\",\"message\":\"Mensagem customizada enviada para os emails dos signat\ários\",\"reminder\":\"WEEKLY\",\"sortable\":\"true\",\"footer\":\"BOTTOM\",\"refusable\":\"true\",\"new_signature_style\":\"true\",\"show_audit_page\":\"false\",\"ignore_cpf\":\"true\",\"email_template_id\":\"1234\",\"deadline_at\":\"2023-11-24T02:59:59.999Z\",\"cc\":[{\"email\":\"email-cc-1@tuamaeaquelaursa.com\"},{\"email\":\"email-cc-2@tuamaeaquelaursa.com\"}],\"expiration\":{\"days_before\":\"7\",\"notify_at\":\"20\\/01\\/2026\"}}; Expected type Boolean at value.refusable; Cannot represent value as boolean: true",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 26
                }
            ]
        }
],
}

```` 

Conseguem me dá um norte.

Abs.

**Comment by vini-md** [comment]
Opa @NandoKstroNet, beleza?

Vc fez o cast do atributo de `"true"` pra `true`, correto?

Deixa eu ver aqui se a lib que ta convertendo pra string novamente.

Se puder me apresenta o seu snippet de código?

**Comment by vini-md** [comment]
@NandoKstroNet fiz o teste e a lib e o autentique funcionam normalmente quando o 
```php
"refusable" => true
```
![Screenshot 2024-03-15 at 13 41 46](https://github.com/vinicinbgs/autentique-v2/assets/16025055/f17f1a53-bc9e-42e0-8456-678476e24797)

O erro que esta apresentando é apenas quando o
```php
"refusable" => "true"
```
![Screenshot 2024-03-15 at 13 40 06](https://github.com/vinicinbgs/autentique-v2/assets/16025055/f2ec131f-611b-45b6-b7b6-986a23cbb32f)

Verifica se o CAST para Boolean está realmente transformando em `true`

**Comment by NandoKstroNet** [comment]
@vinicinbgs meu mano primeiramente obrigado pelo pacote sdk e por seu trampo!!

Conforme seu esclarecimento eu mudei minha forma de iterar o array de dados e fazer o cast correto dos booleans e agora foi!!

Brigadão!!

Desejo sucesso!

**Comment by vini-md** [comment]
Valeu pelo apoio!
