### ISSUE TITLE
Error getting query files

### ISSUE THREAD

**Issue by ijustgotanidea** [vinicinbgs/autentique-v2#51]
I'm trying to configure my Linux server and an error is occurring when trying to access any Documents query.
A quick fix for the problem should be using DIRECTORY_SEPARATOR.

This should work in any OS/Environment.

**Comment by vini-md** [comment]
Can you give me a print of the error?

**Comment by danielbbarcelos** [comment]
Olá @vinicinbgs ! Primeiramente parabéns pelo projeto.

Passei pela mesma situação do @ijustgotanidea . Estava dando o erro:

```
Exception: /var/www/html/my-app/vendor/vinicinbgs/autentique-v2/src/Query.php - 25: file_get_contents(/var/www/html/my-app/vendor/vinicinbgs/autentique-v2/src\resources\documents\create): failed to open stream: No such file or directory 
```

Então vi que o separador de diretório no arquivo `/src/Query.php` está da seguinte forma:

```
  public function __construct()
  {
      $this->folder = __DIR__ . "\\resources\\documents\\";
  }
```

Acredito que já tenha sido corrigido nas versões mais recentes. Mas como uso a versão `^1.0`, estava acusando esse erro também.

Então alterei para o trecho abaixo e deu certo, permitindo o uso da lib em ambientes Linux também:
```
  public function __construct()
  {
        $this->folder = __DIR__ . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'documents' . DIRECTORY_SEPARATOR;
  }
```


@ijustgotanidea tente atualizar a biblioteca para corrigir o erro. Se não puder realizar o update e tiver que seguir na mesma versão (como o meu caso), tente realizar o ajuste mencionado.

**Comment by vini-md** [comment]
@danielbbarcelos Opa tudo bem Daniel? obrigado!

Sim, esse problema é corrigido nas novas versões. Recomendo fortemente atualizar para a mais recente, pois possui bugfixes e mais recursos da API do autentique.
